# Generated by Django 3.0.4 on 2020-04-12 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobSite_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telephone',
            new_name='phone',
        ),
    ]
