# Generated by Django 3.0.4 on 2020-05-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSite_app', '0002_auto_20200413_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='max_salary',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='min_salary',
            field=models.FloatField(default=2600.0),
        ),
    ]
