# Generated by Django 3.0.4 on 2020-05-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSite_app', '0005_joboffer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='category',
            field=models.IntegerField(choices=[(1, 'administracja'), (2, 'architektura'), (3, 'budownictwo'), (4, 'edukacja'), (5, 'farmaceutyka'), (6, 'finanse/ bankowość'), (7, 'gastronomia'), (8, 'IT'), (9, 'inżynieria/ projektowanie'), (12, 'księgowość'), (13, 'kosmetyka'), (14, 'logistyka'), (15, 'motoryzacja'), (16, 'media'), (17, 'praca fizyczna'), (18, 'przemysł/ produkcja'), (19, 'serwis'), (20, 'sprzedaż/ obsługa klienta'), (21, 'transport'), (22, 'inne')], default=22),
        ),
    ]
