# Generated by Django 3.0.4 on 2020-06-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSite_app', '0008_auto_20200525_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
