from django.utils.translation import gettext as _


CATEGORY_CHOICES = (
            (1, _("administracja")),
            (2, _("architektura")),
            (3, _("budownictwo")),
            (4, _("edukacja")),
            (5, _("farmaceutyka")),
            (6, _("finanse/ bankowość")),
            (7, _("gastronomia")),
            (8, _("IT")),
            (9, _("inżynieria/ projektowanie")),
            (12, _("księgowość")),
            (13, _("kosmetyka")),
            (14, _("logistyka")),
            (15, _("motoryzacja")),
            (16, _("media")),
            (17, _("praca fizyczna")),
            (18, _("przemysł/ produkcja")),
            (19, _("serwis")),
            (20, _("sprzedaż/ obsługa klienta")),
            (21, _("transport")),
            (22, _("inne")),
)


CITY_CHOICES = (
    ("Białystok", _("Białystok")),
    ("Bydgoszcz", _("Bydgoszcz")),
    ("Berlin", _("Berlin")),
    ("Frankfurt", _("Frankfurt")),
    ("Gdańsk", _("Gdańsk")),
    ("Gdynia", _("Gdynia")),
    ("Hamburg", _("Hamburg")),
    ("Katowice", _("Katowice")),
    ("Kraków", _("Kraków")),
    ("Kielce", _("Kielce")),
    ("Lyon", _("Lyon")),
    ("Lublin", _("Lublin")),
    ("Łódź", _("Łódź")),
    ("Monachium", _("Monachium")),
    ("Madryt", _("Madryt")),
    ("Nantes", _("Nantes")),
    ("Paryż", _("Paryż")),
    ("Poznań", _("Poznań")),
    ("Rzeszów", _("Rzeszów")),
    ("Saragossa", _("Saragossa")),
    ("Sewilla", _("Sewilla")),
    ("Szczecin", _("Szczecin")),
    ("Tuluza", _("Tuluza")),
    ("Warszawa", _("Warszawa")),
    ("Wrocław", _("Wrocław")),
    ("Inne", _("Inne")),
)